---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka-ns
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: kafka-ns
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: follower
    - port: 3888
      name: election
  selector:
    app: zookeeper
