apiVersion: v1
kind: Service

metadata:
  namespace: kafka-ns
  name: kafka-ui
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
  ports:
  - port: 8090       # porta interna do container
    targetPort: 8080
