apiVersion: v1
kind: Service

metadata:
  namespace: microsservices-ns
  name: proposta-svc
spec:
  type: LoadBalancer
  selector:
    app: proposta-svc
  ports:
    - port: 8083
      targetPort: 8080