apiVersion: v1
kind: Service

metadata:
  name: kafka
  namespace: kafka-ns
  labels:
    app: kafka

spec:
  selector:
    app: kafka

  clusterIP: None

  ports:
    - port: 9092
      name: kafka

---
apiVersion: v1
kind: Service

metadata:
  name: kafka-externo
  namespace: kafka-ns
  labels:
    app: kafka

spec:
  selector:
    app: kafka

  ports:
    - port: 9092
      name: kafka



